#pragma once
#define BLOCK_SIZE_FIELD 16
#define BLOCK_SIZE_FIELD_SUM BLOCK_SIZE_FIELD * BLOCK_SIZE_FIELD
#define NUMBER_OF_PARTICLES 10000
#define TIME_STEP 0.01f
#define BOUNDARY_COLLISION_FORCE 0.3f
#define BLOCK_SIZE 256
#define INITIAL_WINDOW_WIDTH 500
#define INITIAL_WINDOW_HEIGHT 500
#define PROTON 5
#define ELECTRON 5
#define PROTON_FORCE 10.0f
#define ELECTRON_FORCE 10.0f
#define SMALL_PROTON_CHARGE 1.0f
#define SMALL_ELECTRON_CHARGE -1.0f
#define MAX_COLOR 255
#define MIN_COLOR 0
#define INTENSITY_COLOR 256
#define MAX_FPS 35
#define MAX_VELOCITY 2
#define COLORS 4